### ISSUE TITLE
The function of the block in demodulation part? 

### ISSUE THREAD

**Issue by SUSTC2013** [bastibl/gr-ieee802-15-4#10]
I am studying your gr-ieee802-15-4 code now.  But I was a little puzzled. How do  you demodulate the received signal? Why do you use single_pole_iir_filter block, subtract block and Clock recovery MM block? 
Regards,

Thank you!

MarxWolf

**Comment by bastibl** [comment]
I think you should do some research on the functionality of the blocks. The [GNU Radio documentation](http://gnuradio.org/doc/doxygen/) is very good.

Then there is the paper _GNU Radio 802.15.4 En- and Decoding_ by Thomas Schmid that gives an overview and _CMOS RFIC architectures for IEEE 802.15. 4 networks_ by Notor et al. that describes the receive algorithm.

The general idea is to regard O-QPSK as frequency modulation:
- Quadrature demod extracts the phase of the complex symbols
- the IIR filter calcualtes the average phase
- that is subtracts it to center around zero
- the bits are extracted with the MM clock-recovery block
