### ISSUE TITLE
Another question about o-qpsk demodulation in UCLA-ZigBee

### ISSUE THREAD

**Issue by SUSTC2013** [bastibl/gr-ieee802-15-4#12]
Thanks a lot for your advice about the block function in UCLA-ZigBee, but there is another question about the demodulation part. 
I know UCLA-ZigBee treats the o-qpsk modulation as MSK, and I know the reason why this is reasonable. But I referred to the textbook, that there will a delay in I-component to counteract the delay in Q-component in modulation part. I cannot find any delay in the demodulation part. Can you give me more advice?
Thanks a lot.
Regards
Marx

**Comment by bastibl** [comment]
> I know UCLA-ZigBee treats the o-qpsk modulation as MSK, and I know the reason why this is reasonable. 
Then you know that QPSK with an offset in combination with the pulse-shape makes it MSK. Thinking in MSK, there is no offset.
