### ISSUE TITLE
Missing blocks

### ISSUE THREAD

**Issue by SamanthaJDS** [bastibl/gr-ieee802-15-4#13]
Hello,
While attempting to implement this project, I have run across the error of missing blocks (These missing blocks seem to be different than the missing blocks with a "not found in Platform" error that I found when searching for a solution, they just say "not found").  Have these been recently removed or is there a step that might have been missed that would cause this? They appear from both the gr-ieee file and the gr-foo file and both git repositories have been installed.

Thank you

![blockkey](https://cloud.githubusercontent.com/assets/20566519/17004133/c4c34a0c-4e90-11e6-9c87-ddf3665d12e1.PNG)
![missing block](https://cloud.githubusercontent.com/assets/20566519/17004132/c4c2b5e2-4e90-11e6-82a3-9d85d6cf8a10.PNG)

**Comment by bastibl** [comment]
If you installed the block in an uncommon location, you will have to tell GRC where to find them.

https://github.com/bastibl/gr-ieee802-11#troubleshooting
