### ISSUE TITLE
missing blocks

### ISSUE THREAD

**Issue by vsboost** [bastibl/gr-ieee802-15-4#17]
Hi there,

Probably something i overlooked somewhere but i am missing the blocks
ieee802_15_4_css_phy_1
ieee802_15_4_oqpsk_phy_0
In the example transceiver flowgraphs, all other blocks seem to be fine.

Any hints?

**Comment by vsboost** [comment]
My bad, forgot to close and re open gnuradio after generating.. all good now.

**Comment by bastibl** [comment]
See the installation instructions for details:

https://www.wime-project.net/installation/#hierarchical-blocks

**Comment by pbybee** [comment]
Thanks for responding! I must be missing something. Both ~/.gnuradio/grc.conf and /
