### ISSUE TITLE
miss css phy

### ISSUE THREAD

**Issue by FX-XXX** [bastibl/gr-ieee802-15-4#24]
I can't find ieee802.15.4 css phy block,please tell me how to solve it .thank you 
l don't have ~/.gnuradio/config.conf,only have ~/.gnuradio/grc.conf.but after gr-ieee802-15-4/grc l don't have blocks.l don't no what should i do.please heap me.thank you.
![default](https://user-images.githubusercontent.com/18391852/29112246-df7947ca-7d1f-11e7-992a-3926d25a424f.PNG)

**Comment by bastibl** [comment]
It is a hierarchical block. It can be found in the examples folder. Open it in GRC, build it, and reload your blocks (or reopen GRC).

https://www.wime-project.net/installation/
