### ISSUE TITLE
ImportError: No module named ieee802_15_4

### ISSUE THREAD

**Issue by hamzaehsan** [bastibl/gr-ieee802-15-4#26]
![screenshot from 2018-01-27 13-05-41](https://user-images.githubusercontent.com/35734636/35470062-fca72248-0363-11e8-8c30-de95494ec433.png)
(Screenshot attached)
I'm new to gnuradio and ubuntu. I'm facing this Import error and I find confusing how to solve it. Below "Traceback (most recent call last)" is the issue. Kindly help. Thank-you!

**Comment by bastibl** [comment]
![img_20180127_135932](https://user-images.githubusercontent.com/159628/35472642-f3ec70c0-036a-11e8-9f81-6b9b00500dd0.jpg)

**Comment by yuanfangzsp** [comment]
> ![screenshot from 2018-01-27 13-05-41](https://user-images.githubusercontent.com/35734636/35470062-fca72248-0363-11e8-8c30-de95494ec433.png) (Screenshot attached) I'm new to gnuradio and ubuntu. I'm facing this Import error and I find confusing how to solve it. Below "Traceback (most recent call last)" is the issue. Kindly help. Thank-you!

I have the same problem now. How did you solve it? thank you！

**Comment by bastibl** [comment]
The CSS PHY is broken in recent releases. Please use the O-QPSK PHY instead. If you update/port the CSS PHY to the most recent release, please open a PR.
