### ISSUE TITLE
900mhz Does not work

### ISSUE THREAD

**Issue by Crypt0s** [bastibl/gr-ieee802-15-4#3]
The 802.15.4 layer doesn't appear to support 900Mhz Zigbee.

Could we get a version that does support 900Mhz or could you indicate what needs to be changed in order to support 900Mhz operation?

**Comment by sondree** [comment]
@Crypt0s @bastibl

Was this ever added? I would like to use this library with an RTLSDR to listen to 868Mhz Zigbee. I assume the issue for 900Mhz are similar or the same as those for 868Mhz.

In advance thanks

**Comment by bastibl** [comment]
I'm not aware of an extension for 868/900 MHz.

**Comment by sondree** [comment]
Thank you for the quick reply.
