### ISSUE TITLE
The specific process of signal processing

### ISSUE THREAD

**Issue by newtosdr** [bastibl/gr-ieee802-15-4#34]
Hallo, Bastian.
I‘m new to sdr and ubuntu.  I would like to use hackrf one as a detection tool for wifi and wsn (zigbee ) packets, to analyze the structure of the data packets, and get some information from them. I I don't know much about the specific implementation process of your 802.11 and 802.15.4 open source projects. Could you please briefly explain  the specific process of signal processing and packet analysis in your projects to me? In addition, what are your opinions and suggestions on my project? Thank you.

**Comment by bastibl** [comment]
Sorry, but this is a much too broad question. In fact, there are several thesis and papers on these topics.

I'd suggest you start by looking at the standards, the code, and the flow graphs. There are also some papers at https://www.wime-project.net/publications/

Once you have a specific question, it would be great if you could write to the GNU Radio mailing list.
