### ISSUE TITLE
What is the influence of "Select an even decimation to ensure that a halfband filter is enabled."warning?

### ISSUE THREAD

**Issue by GJHLCX** [bastibl/gr-ieee802-15-4#36]
Hi bastibl,
    First of all, I'm very grateful for the code 'gr-ieee802-15-4' you contributed. 
    I met a problem when using it.
After running the grc code, i got this warning:

[32;1m[INFO] [UHD] [39;0mlinux; GNU C++ version 5.4.0 20160609; Boost_105800; UHD_3.11.0.1-37-g2c9087d1
[32;1m[INFO] [USRP2] [39;0mOpening a USRP2/N-Series device...
[32;1m[INFO] [USRP2] [39;0mCurrent recv frame size: 1472 bytes
[32;1m[INFO] [USRP2] [39;0mCurrent send frame size: 1472 bytes
[33;1m[WARNING] [CORES] [39;0mThe requested decimation is odd; the user should expect CIC rolloff.
Select an even decimation to ensure that a halfband filter is enabled.
decimation = dsp_rate/samp_rate -> 25 = (100.000000 MHz)/(4.000000 MHz)

What is the influence of "Select an even decimation to ensure that a halfband filter is enabled."warning?
Does this warning affect the time synchronization in chips (in ieee802.15.4 PHY, symbol to chip ) ?

Thanks,
Jionghong

**Comment by bastibl** [comment]
That's an issue of older SDRs like the N210. It means that the spectrum might not be perfectly flat for some sample rates. I don't think that it will cause performance issues, but you can easily work around this by setting the sample rate to 5M and add a resampler directly after the SDR that resamples 5M -> 4M.
