### ISSUE TITLE
How can I play with it

### ISSUE THREAD

**Issue by tomato990** [bastibl/gr-ieee802-15-4#39]
Now I have successfully installed the project, but I have no idea how to play with it. Are there any more guides or examples about the usages? I really appreciate any help.

**Comment by bastibl** [comment]
Depends on what you are interested in. This is a PHY for IEEE 802.15.4, so you can send and receive ZigBee frames. You can, for example, overhear communication from a device and inspect it in Wireshark. Or you can use a two instances of the PHY to send frames back and forth.
