### ISSUE TITLE
Problem Receiving packets using OQPSK Transceiver 

### ISSUE THREAD

**Issue by rell320** [bastibl/gr-ieee802-15-4#45]
Hello
I'm using the GR-IEEE 802.15.4 OQPSK Transceiver and I'm trying to receive a packet from a XBee ZigBee module and then import that packet to wireshark. However, the file sink is always empty after running the flowgraph. I have the rime stack, socket pdu, message strobe, and packet pad all disabled since I'm simply trying to receive a packet. Is there something I need to configure within the MAC block to do this? 

Tellrell

**Comment by bastibl** [comment]
You asked the very same question on the mailing list and I replied hours ago. I think we should keep the discussion in one place.
