### ISSUE TITLE
Add TUNTAP

### ISSUE THREAD

**Issue by gmartina** [bastibl/gr-ieee802-15-4#47]
Hi Bastian,

Would this module work with a tun/tap (to have IP stack), instead socket PDU?

Thank you 

best regards

**Comment by bastibl** [comment]
It's possible in theory. It's a PHY and it doesn't care what kind of data you put into a frame. The main limitation is that the maximum frame size is quite small, i.e., you'd have to configure a small MTU. One would usually use 6LoWPAN for this.
You can have a look at my gr-ieee802-11 project for an example on how to use TUN/TAP with a flowgraph.

**Comment by gmartina** [comment]
thanks!
