### ISSUE TITLE
Logical Link Control question

### ISSUE THREAD

**Issue by gmartina** [bastibl/gr-ieee802-15-4#49]
Hi again Bastian,

I have tested two similar setups, one with gr-802-11 and the other with gr-802-15-4.

I use iperf v1 tool to test the speed. 802.11 works fine, you can see the Logical Link Control layer.

But 802.15.4 doesnt make iperf work. Can you tell me why? cant it put the logical link control layer itself?  is there something i am missing? 

![Captura de pantalla de 2020-05-11 19-08-25](https://user-images.githubusercontent.com/25131607/81800564-4e5f3100-9513-11ea-8baf-1c67e0ce0f2b.png)
![Captura de pantalla de 2020-05-11 19-29-44](https://user-images.githubusercontent.com/25131607/81800570-50c18b00-9513-11ea-9114-d47f87cb0837.png)

**Comment by bastibl** [comment]
There is no example for using 15-4 with TUN/TAP and it is not trivial. I'm not sure what you did, what I should see in the Wireshark screenshots, and what you mean with "15-4 did not make iperf work"...

**Comment by gmartina** [comment]
I am not using TUN/TAP at all, in neither of them. Just gnuradio PDU sockets.

I use iperf with the folloing commands:

 iperf -c 127.0.0.1  -i 1 -u –p 2000 -t 60 -l 1200 -b 1M
 iperf -s -i 1 –u –p 5000

**Comment by bastibl** [comment]
IEEE 802.15.4 has a maximum frame size of 127 byte (everything including headers). May that be the problem?

**Comment by gmartina** [comment]
In that case, I cannot understand why I can make it to send more than 200 bytes of data.

**Comment by bastibl** [comment]
What PHY are you using?

**Comment by gmartina** [comment]
gr-ieee802-15-4/examples/transceiver_OQPSK.grc    (maint-3.7)

**Comment by bastibl** [comment]
hmm, looks like this implementation allows a maximum frame size of 255, while the standard says it's 127 :-) It uses a Byte for the frame size. Actually one bit of the byte is reserved according to the standard.

![len](https://user-images.githubusercontent.com/159628/81927688-589d3000-95e4-11ea-9d78-07ed67d0b1fd.png)
