### ISSUE TITLE
'ieee802_15_4' has no attribute 'rime_stack'

### ISSUE THREAD

**Issue by darrenyoung23** [bastibl/gr-ieee802-15-4#50]
Hi Bastian,

Trying to runtransceiver_OQPSK (/gr-ieee802-15-4/examples/ieee802_15_4_OQPSK_PHY.grc) however I'm getting following error 

File "transceiver_OQPSK.py", line 134, in __init__
    self.ieee802_15_4_rime_stack_0 = ieee802_15_4.rime_stack([129], [131], [132], [23,42])
AttributeError: module 'ieee802_15_4' has no attribute 'rime_stack'

 Not sure why this is the case, is there something i am missing?

**Comment by bastibl** [comment]
Make sure that:
- you have swig installed, such that Python bindings for C++ blocks are generated in the first place
- the Python module is found, i.e., it's in your PYTHONPATH
- the shared library (libgnuradio-ieee802154.so) is in your LD_LIBRARY_PATH

**Comment by darrenyoung23** [comment]
Thanks, I installed swig, seems libgnuradio-ieee802154.so is missing.

**Comment by darrenyoung23** [comment]
Thanks, I installed swig. seems this error is gone now. however I'm getting following error now.
return _runtime_swig.top_block_sptr_primitive_msg_connect(self, *args)
RuntimeError: invalid msg port in connect() or disconnect()

**Comment by darrenyoung23** [comment]
running with gnuradio-config-info -v 3.8.1.0 , wondering whether this is a gnuradio thing?

**Comment by bastibl** [comment]
So you use GNU Radio v3.8.1.0 with the maint-3.8 branch of this module?
Please make sure that you use the unmodified flowgraphs, i.e., git should show a clean repository. I just tested it with the GNU Radio version and it works here.

**Comment by darrenyoung23** [comment]
You are correct, it's work well with the unmodified flow graph.

**Comment by buttercannfly** [comment]
> Make sure that:
> 
> * you have swig installed, such that Python bindings for C++ blocks are generated in the first place
> * the Python module is found, i.e., it's in your PYTHONPATH
> * the shared library (libgnuradio-ieee802154.so) is in your LD_LIBRARY_PATH

I did the three things but that didnt work though,I have swig installed by 
```
sudo apt install swig
```
then I can import ieee802_15_4 in my python,
my LD_LIBRARY_PATH has a libgnuradio-ieee802_15_4.so,
it seems it has to work now,but it didn't.
