### ISSUE TITLE
Problem installing gr-ieee802-15-4

### ISSUE THREAD

**Issue by jnavarrog** [bastibl/gr-ieee802-15-4#56]
Hi!, first thanks for the development

I am having problem with the installation, I follow the steps but GNU Radio does not recognize the blocks, with gr-foo there is no problem.

I can compile and install without problems, indeed I see the .yml blocks in the correct folder. 

I am using Ubuntu 18.04 clean installation and GNU Radio 3.8.

I tried several times of reinstall all but the result is always the same.

![gnuerror](https://user-images.githubusercontent.com/58449131/119892829-fd00c480-bf10-11eb-98e2-5c881c849b43.png)

Any idea?

Thank you in advance!

**Comment by bastibl** [comment]
Check the output of cmake and the build. Either there was an error and it was not installed at all. Or they were installed in different folders, which you can see from the output of the `make install` step.
