### ISSUE TITLE
'No supported devices found'. Hackrf One added to Transceiver_CSS_USRP.grc file. 

### ISSUE THREAD

**Issue by dominiktopyla** [bastibl/gr-ieee802-15-4#61]
I'm using Gnu Radio 3.9 with gr-foo 3.9 and gr-ieee802-15-4 3.9 on Kali Linux. I added gr-osmosdr module to Gnu Radio. I modified Transceiver_CSS_USRP.grc file by replacing USRP with osmocom. After executing file I got an error:

Executing: transceiver_CSS_USRP.py

Error: failed to enable real-time scheduling.
gr-osmosdr 0.2.0.0 (0.2.0) gnuradio v3.9.6.0-1-gac58f3ba
built-in source types: file rtl_tcp rfspace redpitaya 
Traceback (most recent call last):
  File "/home/lava/gr-ieee802-15-4/examples/transceiver_CSS_USRP.py", line 395, in <module>
    main()
  File "/home/lava/gr-ieee802-15-4/examples/transceiver_CSS_USRP.py", line 373, in main
    tb = top_block_cls()
  File "/home/lava/gr-ieee802-15-4/examples/transceiver_CSS_USRP.py", line 190, in __init__
    self.osmosdr_source_0 = osmosdr.source(
RuntimeError: No supported devices found (check the connection and/or udev rules).

![tansceiver_CSS_USRP](https://user-images.githubusercontent.com/48126787/164543883-9c84de2e-5a82-4f12-aa22-f11659e3beab.png)

I want to capture ZigBee packets with Hackrf One. Does gr-ieee802-15-4 modules are compatible with Hackrf One or I make a mistake in graph?

**Comment by bastibl** [comment]
```
 built-in source types: file rtl_tcp rfspace redpitaya
```
It looks like you compiled gr-osmosdr without HackRF support.
