### ISSUE TITLE
Questions about MSK chip table and the standard chip table

### ISSUE THREAD

**Issue by xinliulab** [bastibl/gr-ieee802-15-4#62]
Dear Bloessl,

I notice you use MSK instead of O-QPSK to build the 802.15.4 transceiver because O-QPSK modulation with half-sine pulse shape is equivalent to MSK. I also read the paper "CMOS RFIC ARCHITECTURES FOR IEEE 802.15.4 NETWORKS". But I found that your transmitter's coding and modulation process satisfies the 802.15.4 standard. Why can my TI packet sniffer not receive the signal when I change the MSK chip table to the standard chip table?

I also use Adam-Pluto + MatLab to build the 802.15.4 transceiver. Their coding and modulation are almost similar to yours. But they use the standard chip table. So when I feed the baseband data created by MatLab to USRP, my TI packet sniffer can not also receive the signal. Is there any difference when transmitting baseband between Pluto SDR and USRP?

Thank you very much for your time and consideration!

Xin

**Comment by bastibl** [comment]
I'm not sure I understand the question. This transceiver uses the standard chip tables. It's just adapted for the MSK-way. It was tested and is interoperable with O-QPSK transceivers out-of-the-box. If it doesn't work, you need to check the firmware of the node and all typical potential issues of SDRs (gain, antenna, etc).
