### ISSUE TITLE
Chunks to symbols mapping

### ISSUE THREAD

**Issue by OxotaKpenkoe** [bastibl/gr-ieee802-15-4#63]
Hi!
First of all i want to thank you for this great work!
my question is about symbol table in "chunks to symbols" block. 
y there are some difference with ieee 802.15.4 standart? 
![mapping_table_ieee](https://user-images.githubusercontent.com/62104960/176142959-1ffdf521-7f84-415c-ba59-8f462b4302e7.JPG)
for example symbol # 14  mapped to this sequence in this block:
(1-1j), (-1+1j), (1+1j), (-1-1j), (-1-1j), (1+1j), (-1+1j), (-1+1j), (-1-1j), (1-1j), (-1-1j), (1-1j), (1+1j), (1-1j), (1+1j), (-1+1j)
but in ieee it is:
  10         01         01      10        00         00        01       11        01       11       10      11       10        00       11        00
so, it must be somethink like:
(1-1j), (-1+1j), (-1+1j), (1-1j), (-1-1j), (-1-1j), (-1+1j), (1+1j), (-1+1j), (1+1j), (1-1j), (1+1j), (1-1j), (-1-1j), (1+1j), (-1-1j)

**Comment by bastibl** [comment]
IIRC, this is due to the strange bit ordering. 14 = 0b1110 -> reversed 0b0111 = 7. The sequence of number 14 is at position 7.

**Comment by OxotaKpenkoe** [comment]
thank you so much!
