### ISSUE TITLE
Wrong crc, and wireshark can not work 

### ISSUE THREAD

**Issue by lic9898** [bastibl/gr-ieee802-15-4#64]
Hi, when I ran the transceiver_CSS_loopback project on Gnuradio 3.10.4, I found a list of message.
![图片](https://user-images.githubusercontent.com/77087259/199224461-d21d4b53-fa29-4849-bffd-0d33273df46b.png)
I didn't change your graph.
![图片](https://user-images.githubusercontent.com/77087259/199225502-3e0f336c-cad1-4224-ad33-e512b349fd84.png)
Then I tried to catch the frame to compare tx frames and rx frames but couldn't launch wireshark. The only message is "wireshark: You can't specify both a live capture and a capture file to be read." But I created the fifo and write a bash file according to your tutorial:
$mkfifo /tmp/zigbee.pcap
$wireshark -k /tmp/zigbee.pcap
Could anyone help me ?

**Comment by bastibl** [comment]
I just worked on the GNU Radio 3.10 branch and also noticed this bug. I didn't implement the CSS Phy and don't use it myself. You could switch to the O-QPSK Phy or need to debug the issue. In the latter case, a PR would be very much appreciated.

**Comment by lic9898** [comment]
OK, thank you. But I don't know what PR is. Could you give me its full name?

**Comment by bastibl** [comment]
I meant that if you find a solution (i.e. a fix for the bug) you should open a Pull Request (PR) here on GitHub.

**Comment by lic9898** [comment]
Fine...I hope so. Thank you for your help
