### ISSUE TITLE
No module named 'foo'

### ISSUE THREAD

**Issue by yuanfangzsp** [bastibl/gr-ieee802-15-4#67]
Hello, I encountered the following problem when running ieee802_15_4_OQPSK_PHY.grc module：

Generating: '/root/.grc_gnuradio/ieee802_15_4_oqpsk_phy.py'

Executing: /usr/bin/python3 -u /root/.grc_gnuradio/ieee802_15_4_oqpsk_phy.py

Traceback (most recent call last):
  File "/root/.grc_gnuradio/ieee802_15_4_oqpsk_phy.py", line 20, in <module>
    import foo
ModuleNotFoundError: No module named 'foo'

But my foo module is already installed。
Can you give me some help？

**Comment by bastibl** [comment]
You have to check where the Python module got installed and make sure that this is found by the python interpreter, for example by setting the PYTHONPATH accordingly.

**Comment by yuanfangzsp** [comment]
Can you recommend any code-related papers? I would like to further understand through the paper, thank you！

**Comment by altonbill** [comment]
I'm running into a similar issue where the blocks are not detected. How would I check where the blocks got installed? And where would I want to put them if I can't find the where the gnu radio config file was installed either

**Comment by bastibl** [comment]
The above error means that the Python module was not found. If your GRC cannot find the blocks that's a different problem. If you didn't install them in a default location, you'll have to tell GNU Radio Companion where to find them. https://www.wime-project.net/installation/#adapt-environment-variables
