### ISSUE TITLE
Block id "ieee802_15_4_oqpsk_phy" not found.

### ISSUE THREAD

**Issue by Wanghaoyu920** [bastibl/gr-ieee802-15-4#69]
![QQ截图20230415212336](https://user-images.githubusercontent.com/66761267/232226785-d6ff0b83-7391-4407-ba75-3c15f31db211.jpg)
I'm new and ran into this issue after the installation was done and wanted to help me with a bit.

**Comment by bastibl** [comment]
This is a hierarchical block. You have to open the corresponding flowgraph ([ieee802_15_4_OQPSK_PHY.grc](https://github.com/bastibl/gr-ieee802-15-4/blob/maint-3.9/examples/ieee802_15_4_OQPSK_PHY.grc)) build it and reopen GNU Radio Companion.
