### ISSUE TITLE
rror: failed to enable real-time scheduling transceiver_OQPSK

### ISSUE THREAD

**Issue by fede-bello** [bastibl/gr-ieee802-15-4#71]
I've been use the diagram transceiver_OQPSK with the loopback, however, i've been having this following error:

Generating: '/home/gnuradio/gr-ieee802-15-4/examples/transceiver_OQPSK.py'
>>> Warning: This flow graph may not have flow control: no audio or RF hardware blocks found. Add a Misc->Throttle block to your flow graph to avoid CPU congestion.

Executing: /usr/bin/python3 -u /home/gnuradio/gr-ieee802-15-4/examples/transceiver_OQPSK.py

Warning: failed to XInitThreads()
Error: failed to enable real-time scheduling.
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-gnuradio'
sender started
gr::log :INFO: foo_packet_pad20 - set_min_output_buffer on block 7 to 65536
gr::log :INFO: tagged_stream_multiply_length0 - set_min_output_buffer on block 11 to 65536
gr::log :INFO: float_to_complex0 - set_min_output_buffer on block 18 to 65536
gr::log :INFO: foo_packet_pad21 - set_min_output_buffer on block 23 to 65536

>>> Done (return code -11)

I don't know if it's an error per se, the program excutes for one second and then aborts. All the connections in the diagram are correct, the UHD blocks are disabled and the Packet Pad enabled:
![image](https://github.com/bastibl/gr-ieee802-15-4/assets/101653254/db2f1934-f019-4987-a09b-a4d24bd7367e)

**Comment by bastibl** [comment]
The actual error is not in the log. There seems to be a segmentation fault. Since GNU Radio introduced some regressions. I'd recommend to use the most recent 3.10 release.
