### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by JayKickliter** [bastibl/gr-ieee802-15-4#8]
I'm happy to some recent contributions to this project project. Do you have some sort of a roadmap or todo list? There's a few things I'd like to contribute, but I want to make sure I'm on duplicating effort. 

Stuff I'd like to implement:

* 900 MHz BPSK PHY
* De-hardcode address data in MAC layer

**Comment by bastibl** [comment]
Hi Jay, thanks for your interest! Actually there is no roadmap, but both projects would be nice to have and I'm not aware that somebody is working on them.
There were already people asking for the 900MHz PHY, so I guess there is interest.

**Comment by JayKickliter** [comment]
Ok, I have a working BPSK packet sink. I've never touched c++ before, so I had translate your original sink into Julia, get it working, and translate it back to c++. The BPSK and OQPSK sinks are so similar that in theory they could be one class, whose parameters determine the symbol mapping/bits per symbol. However, that would require performing the float slicing before the block when processing an OQPSK stream. That's unless your FM OQPSK demodulation scheme can be applied to BPSK (I really don't understand how that works).

I'll submit a pull request soon.

**Comment by bastibl** [comment]
That sounds great, looking forward!

**Comment by bastibl** [comment]
Since this is not really an issue I will mark it as closed. Don't know if there's a nice way of having just a thread for conversation (like in a forum). I hope that's fine.
Looking forward to your pull request.
